;;;
; LoRa MailBox
;
; Copyright (C) 2025, GPL-3.0-or-later, Nicolas Jeanmonod, ouilogique.com
;;

[user_pref-platformio]
default_envs =
    seeed_xiao_nrf52840-tx
    seeed_xiao_esp32s3-rx

[user_pref-env]
build_flags =
    -D DEBUG=true
    -D SENDTO_NTFY=false

[user_pref-seeed_xiao_esp32s3-rx]
upload_port = /dev/cu.usbmodem311101
build_flags =

[user_pref-seeed_xiao_esp32s3-tx]
upload_port = /dev/cu.usbmodem311301
build_flags =

[user_pref-seeed_xiao_nrf52840-tx]
upload_port = /dev/cu.usbmodem3114201
build_flags =
