;;;
; LoRa MailBox
;
; Copyright (C) 2025, GPL-3.0-or-later, Nicolas Jeanmonod, ouilogique.com
;;

[user_pref-seeed_xiao_esp32s3-rx]
upload_port = /dev/cu.usbmodem11101
build_flags =

[user_pref-seeed_xiao_esp32s3-tx]
upload_port = /dev/cu.usbmodem11201
build_flags =

[user_pref-seeed_xiao_nrf52840-tx]
upload_port = /dev/cu.usbmodem114201
build_flags =
